### PR TITLE
Fix filtering clusters by tenant

### LINKED ISSUE #95: Filtering clusters by tenant does not work
According to the documentation, [clusters can be filtered by tenant ID](https://syn.tools/lieutenant-api/references/index.html#_listclusters). This does not work.

## Steps to Reproduce the Problem

    curl -sS -H "$LIEUTENANT_AUTH" "https://${LIEUTENANT_URL}/clusters?tenant=t-xxx" | jq '.[].displayName'

## Actual Behavior
* List of ALL clusters in the API

## Expected Behavior
* List of the specific tenant's clusters.

## Workaround

    curl -sS -H "$LIEUTENANT_AUTH" "https://${LIEUTENANT_URL}/clusters" | jq '.[] | select(.tenant == "t-xxx") | .displayName'

### PR DESCRIPTION
**Pull request by bastjan**
Fixes #95 

Filters clusters by tenant using the `syn.tools/tenant` label added by the operator on reconcile.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] Link this PR to related issues.

### CODE REVIEW

File: pkg/service/cluster.go [hunk 1]
```diff
@@ -25,11 +25,16 @@ const (
 )
 
 // ListClusters lists all clusters
-func (s *APIImpl) ListClusters(c echo.Context, _ api.ListClustersParams) error {
+func (s *APIImpl) ListClusters(c echo.Context, p api.ListClustersParams) error {
 	ctx := c.(*APIContext)
 
+	filterOptions := []client.ListOption{client.InNamespace(s.namespace)}
+	if p.Tenant != nil && *p.Tenant != "" {
+		filterOptions = append(filterOptions, client.MatchingLabels{"syn.tools/tenant": *p.Tenant})
```
Comment (glrf) [inline pkg/service/cluster.go:33]:
```suggestion
		filterOptions = append(filterOptions, client.MatchingLabels{synv1alpha1.LabelNameTenant: *p.Tenant})
```

**Review by glrf — APPROVED** [review]
LGTM, that was even less effort than I expected :sweat_smile:

File: pkg/service/cluster.go (hunk 1 above)
Comment (bastjan) [reply pkg/service/cluster.go:33]: 🤦‍♀️ still in my staged changes
